import ServiceBase from 'api/ServiceBase';
import {
  IssueValidationType,
  OpenissueComment,
  OpenissueGroup,
  OpenissueGroupCategory,
  OpenissueGroupMember,
  OpenIssueMenu,
  OpenIssueRelationship,
  OpenIssueSearch
} from './openIssue.types';
import { OpenIssueType } from 'pages/qms/qms/open-issue';
import { DLibrary } from 'api/system/library/library.types';
import { ActivityLog, ActivityAction } from './activityLog.types';

// 개발 모드 인증 우회 설정
const DEV_BYPASS_AUTH = import.meta.env.VITE_DEV_BYPASS_AUTH === 'true';

// Mock 카테고리 데이터 - labelKey는 번역 키
const mockCategoryData: DLibrary[] = [
  { oid: 1, name: 'DEPT', korNm: '부서별', engNm: 'By Department', labelKey: 'category-by-dept', isUse: 1 },
  { oid: 2, name: 'DEV', korNm: '개발별', engNm: 'By Development', labelKey: 'category-by-dev', isUse: 1 }
];

// Mock 메뉴 데이터 (사이드바 그룹) - 확장된 버전, labelKey는 번역 키
const mockMenuData: Record<string, OpenIssueMenu[]> = {
  DEPT: [
    {
      key: '1',
      title: '영업팀',
      labelKey: 'dept-sales',
      type: 'DEPT',
      data: { oid: 1, name: '영업팀', groupType: 'DEPT' },
      children: [
        { key: '11', title: '수주 추진', labelKey: 'group-order-pursuit', type: 'GROUP', data: { oid: 11 }, children: [] },
        { key: '12', title: '기술 검토', labelKey: 'group-tech-review', type: 'GROUP', data: { oid: 12 }, children: [] },
        { key: '13', title: '단가 조정', labelKey: 'group-price-adjust', type: 'GROUP', data: { oid: 13 }, children: [] },
        { key: '14', title: '신규 고객 개발', labelKey: 'group-new-customer', type: 'GROUP', data: { oid: 14 }, children: [] },
        { key: '15', title: '견적 관리', labelKey: 'group-quote-mgmt', type: 'GROUP', data: { oid: 15 }, children: [] },
        { key: '16', title: '단종 관리', labelKey: 'group-discontinue', type: 'GROUP', data: { oid: 16 }, children: [] }
      ]
    },
    {
      key: '2',
      title: '품질관리팀',
      labelKey: 'dept-quality',
      type: 'DEPT',
      data: { oid: 2, name: '품질관리팀', groupType: 'DEPT' },
      children: [
        { key: '21', title: '품질 이슈', labelKey: 'group-quality-issue', type: 'GROUP', data: { oid: 21 }, children: [] },
        { key: '22', title: '클레임 대응', labelKey: 'group-claim-response', type: 'GROUP', data: { oid: 22 }, children: [] },
        { key: '23', title: '고객 감사', labelKey: 'group-customer-audit', type: 'GROUP', data: { oid: 23 }, children: [] },
        { key: '24', title: '내부 품질', labelKey: 'group-internal-quality', type: 'GROUP', data: { oid: 24 }, children: [] },
        { key: '25', title: '불량 분석', labelKey: 'group-defect-analysis', type: 'GROUP', data: { oid: 25 }, children: [] }
      ]
    },
    {
      key: '3',
      title: '기술팀',
      labelKey: 'dept-tech',
      type: 'DEPT',
      data: { oid: 3, name: '기술팀', groupType: 'DEPT' },
      children: [
        { key: '31', title: '기술 검토', labelKey: 'group-tech-review', type: 'GROUP', data: { oid: 31 }, children: [] },
        { key: '32', title: 'TR 대응', labelKey: 'group-tr-response', type: 'GROUP', data: { oid: 32 }, children: [] },
        { key: '33', title: '설계 변경', labelKey: 'group-design-change', type: 'GROUP', data: { oid: 33 }, children: [] },
        { key: '34', title: '시험 평가', labelKey: 'group-test-eval', type: 'GROUP', data: { oid: 34 }, children: [] },
        { key: '35', title: '양산 지원', labelKey: 'group-mass-support', type: 'GROUP', data: { oid: 35 }, children: [] }
      ]
    },
    {
      key: '4',
      title: '경영기획팀',
      labelKey: 'dept-planning',
      type: 'DEPT',
      data: { oid: 4, name: '경영기획팀', groupType: 'DEPT' },
      children: [
        { key: '41', title: 'M&A 추진', labelKey: 'group-ma', type: 'GROUP', data: { oid: 41 }, children: [] },
        { key: '42', title: '매출 관리', labelKey: 'group-sales-mgmt', type: 'GROUP', data: { oid: 42 }, children: [] },
        { key: '43', title: '투자 계획', labelKey: 'group-investment', type: 'GROUP', data: { oid: 43 }, children: [] },
        { key: '44', title: '사업 전략', labelKey: 'group-business-strategy', type: 'GROUP', data: { oid: 44 }, children: [] },
        { key: '45', title: '회사 홍보', labelKey: 'group-company-pr', type: 'GROUP', data: { oid: 45 }, children: [] }
      ]
    },
    {
      key: '5',
      title: '구매팀',
      labelKey: 'dept-procurement',
      type: 'DEPT',
      data: { oid: 5, name: '구매팀', groupType: 'DEPT' },
      children: [
        { key: '51', title: '원소재 관리', labelKey: 'group-material-mgmt', type: 'GROUP', data: { oid: 51 }, children: [] },
        { key: '52', title: '협력업체 관리', labelKey: 'group-vendor-mgmt', type: 'GROUP', data: { oid: 52 }, children: [] },
        { key: '53', title: '납기 관리', labelKey: 'group-delivery-mgmt', type: 'GROUP', data: { oid: 53 }, children: [] },
        { key: '54', title: '원가 절감', labelKey: 'group-cost-reduce', type: 'GROUP', data: { oid: 54 }, children: [] }
      ]
    },
    {
      key: '6',
      title: '생산팀',
      labelKey: 'dept-production',
      type: 'DEPT',
      data: { oid: 6, name: '생산팀', groupType: 'DEPT' },
      children: [
        { key: '61', title: '양산 이슈', labelKey: 'group-mass-issue', type: 'GROUP', data: { oid: 61 }, children: [] },
        { key: '62', title: '설비 관리', labelKey: 'group-facility-mgmt', type: 'GROUP', data: { oid: 62 }, children: [] },
        { key: '63', title: '라인 증설', labelKey: 'group-line-expand', type: 'GROUP', data: { oid: 63 }, children: [] },
        { key: '64', title: '생산성 향상', labelKey: 'group-productivity', type: 'GROUP', data: { oid: 64 }, children: [] }
      ]
    },
    {
      key: '7',
      title: 'IT팀',
      labelKey: 'dept-it',
      type: 'DEPT',
      data: { oid: 7, name: 'IT팀', groupType: 'DEPT' },
      children: [
        { key: '71', title: 'ERP 관리', labelKey: 'group-erp-mgmt', type: 'GROUP', data: { oid: 71 }, children: [] },
        { key: '72', title: '시스템 개선', labelKey: 'group-system-improve', type: 'GROUP', data: { oid: 72 }, children: [] },
        { key: '73', title: '보안 관리', labelKey: 'group-security-mgmt', type: 'GROUP', data: { oid: 73 }, children: [] }
      ]
    },
    {
      key: '8',
      title: '해외법인',
      labelKey: 'dept-overseas',
      type: 'DEPT',
      data: { oid: 8, name: '해외법인', groupType: 'DEPT' },
      children: [
        { key: '81', title: '인도법인 (WII)', labelKey: 'group-india-wii', type: 'GROUP', data: { oid: 81 }, children: [] },
        { key: '82', title: '중국법인 (WRC)', labelKey: 'group-china-wrc', type: 'GROUP', data: { oid: 82 }, children: [] },
        { key: '83', title: '태국법인 (WRT)', labelKey: 'group-thailand-wrt', type: 'GROUP', data: { oid: 83 }, children: [] }
      ]
    }
  ],
  DEV: [
    {
      key: '100',
      title: 'HV PTC Heater',
      type: 'DEV',
      data: { oid: 100, name: 'HV PTC Heater', groupType: 'DEV' },
      children: [
        { key: '101', title: 'SANDEN 5kW', type: 'PROJECT', data: { oid: 101 }, children: [] },
        { key: '102', title: 'MAZDA 5Q45V', type: 'PROJECT', data: { oid: 102 }, children: [] },
        { key: '103', title: 'Xiaomi MMA', type: 'PROJECT', data: { oid: 103 }, children: [] },
        { key: '104', title: 'VALEO NOVA', type: 'PROJECT', data: { oid: 104 }, children: [] },
        { key: '105', title: 'Hanon WH', type: 'PROJECT', data: { oid: 105 }, children: [] },
        { key: '106', title: 'YUXIN EV', type: 'PROJECT', data: { oid: 106 }, children: [] },
        { key: '107', title: 'ROX 500W', type: 'PROJECT', data: { oid: 107 }, children: [] },
        { key: '108', title: '东风轩辕', type: 'PROJECT', data: { oid: 108 }, children: [] }
      ]
    },
    {
      key: '200',
      title: 'LV PTC Heater',
      type: 'DEV',
      data: { oid: 200, name: 'LV PTC Heater', groupType: 'DEV' },
      children: [
        { key: '201', title: 'SUBROS 240W', type: 'PROJECT', data: { oid: 201 }, children: [] },
        { key: '202', title: 'Daihatsu', type: 'PROJECT', data: { oid: 202 }, children: [] },
        { key: '203', title: 'MAHINDRA P212', type: 'PROJECT', data: { oid: 203 }, children: [] },
        { key: '204', title: 'TATA TBD', type: 'PROJECT', data: { oid: 204 }, children: [] },
        { key: '205', title: 'DENSO DC', type: 'PROJECT', data: { oid: 205 }, children: [] },
        { key: '206', title: 'MARUTI e-Tractor', type: 'PROJECT', data: { oid: 206 }, children: [] },
        { key: '207', title: 'Yuanmi', type: 'PROJECT', data: { oid: 207 }, children: [] }
      ]
    },
    {
      key: '300',
      title: 'Coolant Valve',
      type: 'DEV',
      data: { oid: 300, name: 'Coolant Valve', groupType: 'DEV' },
      children: [
        { key: '301', title: 'SUZUKI 4Way', type: 'PROJECT', data: { oid: 301 }, children: [] },
        { key: '302', title: 'SUZUKI 6Way', type: 'PROJECT', data: { oid: 302 }, children: [] },
        { key: '303', title: 'DENSO CV', type: 'PROJECT', data: { oid: 303 }, children: [] }
      ]
    },
    {
      key: '400',
      title: 'Coolant Heater',
      type: 'DEV',
      data: { oid: 400, name: 'Coolant Heater', groupType: 'DEV' },
      children: [
        { key: '401', title: 'LANTU H37', type: 'PROJECT', data: { oid: 401 }, children: [] },
        { key: '402', title: 'SANDEN CH', type: 'PROJECT', data: { oid: 402 }, children: [] },
        { key: '403', title: 'Songz ZS11', type: 'PROJECT', data: { oid: 403 }, children: [] }
      ]
    },
    {
      key: '500',
      title: 'Air PTC Heater',
      type: 'DEV',
      data: { oid: 500, name: 'Air PTC Heater', groupType: 'DEV' },
      children: [
        { key: '501', title: 'EULER MOTORS', type: 'PROJECT', data: { oid: 501 }, children: [] },
        { key: '502', title: 'JCS C85', type: 'PROJECT', data: { oid: 502 }, children: [] }
      ]
    },
    {
      key: '600',
      title: 'Control Unit',
      type: 'DEV',
      data: { oid: 600, name: 'Control Unit', groupType: 'DEV' },
      children: [
        { key: '601', title: 'Joysonquin R11', type: 'PROJECT', data: { oid: 601 }, children: [] },
        { key: '602', title: 'SUBARU 500W', type: 'PROJECT', data: { oid: 602 }, children: [] }
      ]
    },
    {
      key: '700',
      title: 'Actuator',
      type: 'DEV',
      data: { oid: 700, name: 'Actuator', groupType: 'DEV' },
      children: [
        { key: '701', title: 'Songz EVG-1', type: 'PROJECT', data: { oid: 701 }, children: [] },
        { key: '702', title: 'LIN Stepper', type: 'PROJECT', data: { oid: 702 }, children: [] }
      ]
    }
  ]
};

// Mock Open Issue 데이터 (Excel 데이터 기반) - 모든 필드 완성
const mockOpenIssueData: OpenIssueType[] = [
  // ===== 영업팀 이슈 =====
  {
    oid: 89,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '인도',
    oemLibNm: 'SUBROS',
    category: '사양',
    itemNm: 'LV PTC Heater',
    projectNm: '240W',
    description: '수주 대응\n20260205: 고객 요청사항 검토 완료\n20260204: 수주 관련 내부 미팅 진행',
    importance: '2',
    importanceNm: '중',
    status: 'OPEN',
    strDt: '2026-02-04',
    finDt: '2026-03-15',
    duration: '39',
    sop: '2027-06-01',
    volum: '75000',
    remark: '인도 시장 확대 전략',
    managerTeam: '영업팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-089',
    issueStateNm: '진행중',
    issueManagerNm: '채지훈',
    assignedTo: '채지훈',
    openIssueGroup: 11,
    openIssueCategoryOid: 1,
    groupCategoryOid: 1
  },
  {
    oid: 88,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '일본',
    oemLibNm: 'SUZUKI',
    category: '사양',
    itemNm: 'Coolant Valve',
    projectNm: '4Way/6Way',
    description: '기술검토\n20260212: 스즈키 방문 제품 설명회 일정 조율\n20260203: 4 Way, 6 Way 등록 관련 실무자 미팅 진행',
    importance: '3',
    importanceNm: '상',
    status: 'OPEN',
    strDt: '2026-02-02',
    finDt: '2026-07-01',
    duration: '149',
    sop: '2028-03-01',
    volum: '120000',
    remark: '일본 시장 신규 진입',
    managerTeam: '기술팀',
    management: 'true',
    report: 'Y',
    issueNo: 'OI-2026-088',
    issueStateNm: '검토중',
    issueManagerNm: '한청훤',
    assignedTo: '한청훤',
    openIssueGroup: 31,
    openIssueCategoryOid: 3,
    groupCategoryOid: 1
  },
  {
    oid: 87,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '본사',
    oemLibNm: 'All',
    category: '기타',
    itemNm: 'All',
    projectNm: '매출 Recovery',
    description: '26년 전사 매출액 Recovery 방안\n20260128: 실적추이 현황 update\n20260126: 26년 전사 매출액 Recovery 방안 보고 작성',
    importance: '2',
    importanceNm: '중',
    status: 'OPEN',
    strDt: '2026-01-26',
    finDt: '2026-06-30',
    duration: '155',
    sop: '',
    volum: '',
    remark: '경영진 지시사항',
    managerTeam: '경영기획팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-087',
    issueStateNm: '진행중',
    issueManagerNm: '김태호',
    assignedTo: '김태호',
    openIssueGroup: 42,
    openIssueCategoryOid: 4,
    groupCategoryOid: 1
  },
  {
    oid: 86,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '일본',
    oemLibNm: 'SANDEN',
    category: '사양',
    itemNm: 'HV PTC Heater',
    projectNm: 'SANDEN 5kW',
    description: '수주 대응\n20260213: 산덴 방문 신규 제품 설명회 일정 조율\n프로젝트: SANDEN 5kW HV PTC\n총 물량: 30K (6년)\nSOP: 2030.06 (임시)',
    importance: '3',
    importanceNm: '상',
    status: 'OPEN',
    strDt: '2026-01-28',
    finDt: '2026-07-01',
    duration: '154',
    sop: '2030-06-01',
    volum: '200000',
    remark: '일본 시장 주력 프로젝트',
    managerTeam: '영업팀',
    management: 'true',
    report: 'Y',
    issueNo: 'OI-2026-086',
    issueStateNm: '진행중',
    issueManagerNm: '채지훈',
    assignedTo: '채지훈',
    openIssueGroup: 11,
    openIssueCategoryOid: 1,
    groupCategoryOid: 1
  },
  {
    oid: 85,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '중국',
    oemLibNm: 'Songz',
    category: '기타',
    itemNm: 'Actuator',
    projectNm: 'EVG-1',
    description: '양산\n20260127: EVG-1 관련 PO 접수, 제품 도착 확인 중\n20260125: 초도품 납품 완료',
    importance: '1',
    importanceNm: '하',
    status: 'OPEN',
    strDt: '2026-01-27',
    finDt: '2026-03-31',
    duration: '63',
    sop: '2026-01-01',
    volum: '15000',
    remark: '양산 진행 중',
    managerTeam: '생산팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-085',
    issueStateNm: '진행중',
    issueManagerNm: '김태호',
    assignedTo: '김태호',
    openIssueGroup: 61,
    openIssueCategoryOid: 6,
    groupCategoryOid: 1
  },
  {
    oid: 84,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '본사',
    oemLibNm: 'All',
    category: '기타',
    itemNm: 'All',
    projectNm: '원소재 인상',
    description: '원소재 인상\n20260128: ASIA/NA/EU 반영 완료\n20260127: 글로벌 원소재 인상 현황 update',
    importance: '2',
    importanceNm: '중',
    status: 'OPEN',
    strDt: '2026-01-26',
    finDt: '2026-04-30',
    duration: '94',
    sop: '',
    volum: '',
    remark: '글로벌 원자재 가격 상승',
    managerTeam: '구매팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-084',
    issueStateNm: '진행중',
    issueManagerNm: '김태호',
    assignedTo: '김태호',
    openIssueGroup: 51,
    openIssueCategoryOid: 5,
    groupCategoryOid: 1
  },
  {
    oid: 83,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '본사',
    oemLibNm: 'All',
    category: '기타',
    itemNm: 'All',
    projectNm: '회사소개서',
    description: '회사소개서 업데이트\n20260129: 25년 실적자료 업데이트 완료\n2026 회사소개서 update',
    importance: '2',
    importanceNm: '중',
    status: 'OPEN',
    strDt: '2026-01-21',
    finDt: '2026-02-28',
    duration: '38',
    sop: '',
    volum: '',
    remark: '마케팅 자료',
    managerTeam: '경영기획팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-083',
    issueStateNm: '진행중',
    issueManagerNm: '김태호',
    assignedTo: '김태호',
    openIssueGroup: 45,
    openIssueCategoryOid: 4,
    groupCategoryOid: 1
  },
  {
    oid: 81,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '중국',
    oemLibNm: 'LANTU',
    category: '기타',
    itemNm: 'Coolant Heater',
    projectNm: 'H37',
    description: '단가 조정\n20260128: 1월 단가조정 반영완료 진행(3% CR)\n26년 단가 조정\nLANTU 단가 인하 요구(10%)\n - 25년 납품 실적:3400대',
    importance: '2',
    importanceNm: '중',
    status: 'OPEN',
    strDt: '2026-01-23',
    finDt: '2026-02-06',
    duration: '14',
    sop: '2024-01-01',
    volum: '4000',
    remark: '단가 협상 진행 중',
    managerTeam: '영업팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-081',
    issueStateNm: '진행중',
    issueManagerNm: '김태호',
    assignedTo: '김태호',
    openIssueGroup: 13,
    openIssueCategoryOid: 1,
    groupCategoryOid: 1
  },
  {
    oid: 74,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '중국',
    oemLibNm: 'NINGBO ROCKET',
    category: '기타',
    itemNm: 'All',
    projectNm: 'WRC 투자유치',
    description: 'WRC 지분 매각 협상 및 합작 추진\nWRC 5개사 관련 자료 업데이트 실무자 미팅 진행(26/01/23)',
    importance: '2',
    importanceNm: '중',
    status: 'OPEN',
    strDt: '2026-01-22',
    finDt: '2026-04-30',
    duration: '98',
    sop: '',
    volum: '',
    remark: '전략적 투자 유치',
    managerTeam: '경영기획팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-074',
    issueStateNm: '진행중',
    issueManagerNm: '한청훤',
    assignedTo: '한청훤',
    openIssueGroup: 43,
    openIssueCategoryOid: 4,
    groupCategoryOid: 1
  },
  {
    oid: 68,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '해외',
    oemLibNm: 'TBD',
    category: '기타',
    itemNm: 'All',
    projectNm: '우리산업 해외 M&A',
    description: '매출 확대 위한 해외(일본, 인도, 동남아시아) 해외 기업 M&A추진\n20260201: 인도 기업 2개사 실사 진행 중',
    importance: '2',
    importanceNm: '중',
    status: 'OPEN',
    strDt: '2025-12-01',
    finDt: '2026-05-31',
    duration: '181',
    sop: '',
    volum: '',
    remark: '장기 전략 프로젝트',
    managerTeam: '경영기획팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-068',
    issueStateNm: '진행중',
    issueManagerNm: '박상무',
    assignedTo: '박상무',
    openIssueGroup: 41,
    openIssueCategoryOid: 4,
    groupCategoryOid: 1
  },
  {
    oid: 67,
    type: 'DEPT',
    placeOfIssue: '고객',
    productionSite: '일본',
    oemLibNm: 'DENSO',
    category: '사양',
    itemNm: 'LV PTC Heater',
    projectNm: 'DC',
    description: '수주 추진\n20260202: 견적 제출 완료\n20260125: 고객 요청사항 접수',
    importance: '2',
    importanceNm: '중',
    status: 'OPEN',
    strDt: '2026-01-20',
    finDt: '2026-02-06',
    duration: '17',
    sop: '2027-04-01',
    volum: '65000',
    remark: 'DENSO 신규 프로젝트',
    managerTeam: '영업팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-067',
    issueStateNm: '진행중',
    issueManagerNm: '이영업',
    assignedTo: '이영업',
    openIssueGroup: 11,
    openIssueCategoryOid: 1,
    groupCategoryOid: 1
  },
  {
    oid: 66,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '본사',
    oemLibNm: 'Songz',
    category: '기타',
    itemNm: 'Coolant Heater',
    projectNm: 'ZS11, EP33',
    description: '단종 관리\n20260201: 최종 납품 일정 협의\n단종 예정 제품 관리',
    importance: '1',
    importanceNm: '하',
    status: 'OPEN',
    strDt: '2026-01-20',
    finDt: '2026-02-10',
    duration: '21',
    sop: '',
    volum: '',
    remark: '단종 처리 진행',
    managerTeam: '영업팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-066',
    issueStateNm: '진행중',
    issueManagerNm: '정단종',
    assignedTo: '정단종',
    openIssueGroup: 16,
    openIssueCategoryOid: 1,
    groupCategoryOid: 1
  },
  {
    oid: 65,
    type: 'DEPT',
    placeOfIssue: '고객',
    productionSite: '중국',
    oemLibNm: 'ROX',
    category: '사양',
    itemNm: 'HV PTC Heater',
    projectNm: '500W(435W)',
    description: '수주 추진\n20260130: 기술 사양 협의 완료\n20260120: 초기 견적 제출',
    importance: '2',
    importanceNm: '중',
    status: 'OPEN',
    strDt: '2026-01-16',
    finDt: '2026-03-31',
    duration: '74',
    sop: '2029-01-01',
    volum: '84000',
    remark: '신규 고객 개발',
    managerTeam: '영업팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-065',
    issueStateNm: '검토중',
    issueManagerNm: '최영업',
    assignedTo: '최영업',
    openIssueGroup: 14,
    openIssueCategoryOid: 1,
    groupCategoryOid: 1
  },
  {
    oid: 64,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '본사',
    oemLibNm: 'All',
    category: '기타',
    itemNm: 'All',
    projectNm: 'ERP Update',
    description: 'ERP 시스템 업데이트\n20260114: 업데이트 완료\n20260112: 시스템 점검 시작',
    importance: '1',
    importanceNm: '하',
    status: 'CLOSE',
    strDt: '2026-01-12',
    finDt: '2026-01-14',
    duration: '2',
    sop: '',
    volum: '',
    remark: 'IT 정기 업데이트',
    managerTeam: 'IT팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-064',
    issueStateNm: '완료',
    issueManagerNm: '김IT',
    assignedTo: '김IT',
    openIssueGroup: 71,
    openIssueCategoryOid: 7,
    groupCategoryOid: 1
  },
  // ===== 품질관리팀 이슈 =====
  {
    oid: 63,
    type: 'DEPT',
    placeOfIssue: '고객',
    productionSite: '중국',
    oemLibNm: 'Joysonquin',
    category: '품질',
    itemNm: 'Control Unit',
    projectNm: 'R11',
    description: '품질 이슈 대응\n20260128: 불량 원인 분석 완료\n20260120: 고객 클레임 접수',
    importance: '1',
    importanceNm: '하',
    status: 'OPEN',
    strDt: '2026-01-14',
    finDt: '2026-01-30',
    duration: '16',
    sop: '',
    volum: '',
    remark: '품질 개선 대책 수립',
    managerTeam: '품질관리팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-063',
    issueStateNm: '검토중',
    issueManagerNm: '박품질',
    assignedTo: '박품질',
    openIssueGroup: 21,
    openIssueCategoryOid: 2,
    groupCategoryOid: 1
  },
  {
    oid: 62,
    type: 'DEPT',
    placeOfIssue: '고객',
    productionSite: '인도',
    oemLibNm: 'EULER MOTORS',
    category: '사양',
    itemNm: 'Air PTC Heater',
    projectNm: 'LIN Stepper',
    description: '영업 대응\n20260115: 기술 미팅 진행\n20260112: 초기 문의 접수',
    importance: '1',
    importanceNm: '하',
    status: 'OPEN',
    strDt: '2026-01-12',
    finDt: '2026-01-16',
    duration: '4',
    sop: '2027-12-01',
    volum: '25000',
    remark: '인도 신규 고객',
    managerTeam: '영업팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-062',
    issueStateNm: '진행중',
    issueManagerNm: '김인도',
    assignedTo: '김인도',
    openIssueGroup: 14,
    openIssueCategoryOid: 1,
    groupCategoryOid: 1
  },
  {
    oid: 61,
    type: 'DEPT',
    placeOfIssue: '고객',
    productionSite: '중국',
    oemLibNm: 'Yuanmi',
    category: '사양',
    itemNm: 'LV PTC Heater',
    projectNm: 'Yuanmi EV',
    description: '수주 추진\n20260201: 2차 견적 제출\n20260115: 초기 견적 검토',
    importance: '2',
    importanceNm: '중',
    status: 'OPEN',
    strDt: '2026-01-05',
    finDt: '2026-02-28',
    duration: '54',
    sop: '2028-06-01',
    volum: '180000',
    remark: '중국 신규 EV 고객',
    managerTeam: '영업팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-061',
    issueStateNm: '진행중',
    issueManagerNm: '이중국',
    assignedTo: '이중국',
    openIssueGroup: 11,
    openIssueCategoryOid: 1,
    groupCategoryOid: 1
  },
  {
    oid: 58,
    type: 'DEPT',
    placeOfIssue: '고객',
    productionSite: '인도',
    oemLibNm: 'SUBROS',
    category: '품질',
    itemNm: 'LV PTC Heater',
    projectNm: 'R11',
    description: '품질 이슈 대응\n20260114: 대책서 제출 완료\n20260107: 품질 이슈 접수',
    importance: '2',
    importanceNm: '중',
    status: 'OPEN',
    strDt: '2026-01-07',
    finDt: '2026-01-16',
    duration: '9',
    sop: '',
    volum: '',
    remark: '품질 클레임 대응',
    managerTeam: '품질관리팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-058',
    issueStateNm: '검토중',
    issueManagerNm: '최품질',
    assignedTo: '최품질',
    openIssueGroup: 22,
    openIssueCategoryOid: 2,
    groupCategoryOid: 1
  },
  {
    oid: 57,
    type: 'DEPT',
    placeOfIssue: '고객',
    productionSite: '중국',
    oemLibNm: 'Songz',
    category: '품질',
    itemNm: 'Coolant Heater',
    projectNm: 'ZS11',
    description: '품질 이슈 대응\n20260110: 원인 분석 완료\n20260107: 불량 접수',
    importance: '1',
    importanceNm: '하',
    status: 'CLOSE',
    strDt: '2026-01-07',
    finDt: '2026-01-12',
    duration: '5',
    sop: '',
    volum: '',
    remark: '조기 해결 완료',
    managerTeam: '품질관리팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-057',
    issueStateNm: '완료',
    issueManagerNm: '정품질',
    assignedTo: '정품질',
    openIssueGroup: 21,
    openIssueCategoryOid: 2,
    groupCategoryOid: 1
  },
  {
    oid: 56,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '해외',
    oemLibNm: 'TBD',
    category: '기타',
    itemNm: 'All',
    projectNm: 'Sales Agent 확보',
    description: 'Sales Agent 발굴\n20260201: 인도네시아, 베트남 후보사 조사 중\n20260107: 동남아 시장 진출 계획 수립',
    importance: '2',
    importanceNm: '중',
    status: 'OPEN',
    strDt: '2026-01-07',
    finDt: '2026-02-27',
    duration: '51',
    sop: '',
    volum: '',
    remark: '해외 영업망 확대',
    managerTeam: '영업팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-056',
    issueStateNm: '진행중',
    issueManagerNm: '박해외',
    assignedTo: '박해외',
    openIssueGroup: 14,
    openIssueCategoryOid: 1,
    groupCategoryOid: 1
  },
  {
    oid: 55,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '중국',
    oemLibNm: 'JCS',
    category: '기타',
    itemNm: 'Air PTC Heater',
    projectNm: 'C85',
    description: '단가 인상 협의\n20260201: 고객 협의 진행 중\n20260105: 단가 인상 요청서 제출',
    importance: '2',
    importanceNm: '중',
    status: 'OPEN',
    strDt: '2026-01-05',
    finDt: '2026-06-30',
    duration: '176',
    sop: '2024-01-01',
    volum: '35000',
    remark: '원가 상승 반영',
    managerTeam: '영업팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-055',
    issueStateNm: '진행중',
    issueManagerNm: '한단가',
    assignedTo: '한단가',
    openIssueGroup: 13,
    openIssueCategoryOid: 1,
    groupCategoryOid: 1
  },
  // ===== 대형 프로젝트 =====
  {
    oid: 54,
    type: 'DEPT',
    placeOfIssue: '고객',
    productionSite: '중국',
    oemLibNm: '东风轩辕(Xuānyuán)',
    category: '사양',
    itemNm: 'HV PTC Heater',
    projectNm: '东风轩辕',
    description: '수주 추진\n20260125: 기술 사양 협의 완료\n20260110: 초기 견적 검토\n대형 프로젝트 수주 추진 중',
    importance: '3',
    importanceNm: '상',
    status: 'OPEN',
    strDt: '2025-12-12',
    finDt: '2026-01-30',
    duration: '49',
    sop: '2028-01-01',
    volum: '500000',
    remark: '중국 대형 OEM 프로젝트',
    managerTeam: '영업팀',
    management: 'true',
    report: 'Y',
    issueNo: 'OI-2026-054',
    issueStateNm: '진행중',
    issueManagerNm: '왕중국',
    assignedTo: '왕중국',
    openIssueGroup: 11,
    openIssueCategoryOid: 1,
    groupCategoryOid: 2
  },
  {
    oid: 52,
    type: 'DEPT',
    placeOfIssue: '고객',
    productionSite: '중국',
    oemLibNm: 'Xiaomi',
    category: '사양',
    itemNm: 'HV PTC Heater',
    projectNm: 'MMA',
    description: '수주 추진\n20260105: 최종 사양 확정\n20251220: 기술 미팅 2차 진행\n샤오미 전기차 HV PTC 프로젝트',
    importance: '3',
    importanceNm: '상',
    status: 'OPEN',
    strDt: '2025-11-23',
    finDt: '2026-01-08',
    duration: '46',
    sop: '2027-12-31',
    volum: '1700000',
    remark: '전략적 대형 프로젝트',
    managerTeam: '영업팀',
    management: 'true',
    report: 'Y',
    issueNo: 'OI-2026-052',
    issueStateNm: '검토중',
    issueManagerNm: '채지훈',
    assignedTo: '채지훈',
    openIssueGroup: 11,
    openIssueCategoryOid: 1,
    groupCategoryOid: 2
  },
  {
    oid: 51,
    type: 'DEPT',
    placeOfIssue: '고객',
    productionSite: '한국',
    oemLibNm: 'Hanon',
    category: '사양',
    itemNm: 'HV PTC Heater',
    projectNm: 'WH',
    description: '수주 추진\n20260201: 2차 기술 검토 완료\n20260110: 사양 협의 진행\n한온 프로젝트 수주 추진',
    importance: '3',
    importanceNm: '상',
    status: 'OPEN',
    strDt: '2025-12-05',
    finDt: '2026-06-30',
    duration: '207',
    sop: '2027-12-31',
    volum: '2500000',
    remark: '국내 대형 프로젝트',
    managerTeam: '영업팀',
    management: 'true',
    report: 'Y',
    issueNo: 'OI-2026-051',
    issueStateNm: '검토중',
    issueManagerNm: '김한온',
    assignedTo: '김한온',
    openIssueGroup: 11,
    openIssueCategoryOid: 1,
    groupCategoryOid: 2
  },
  // ===== 기술팀 이슈 =====
  {
    oid: 47,
    type: 'DEPT',
    placeOfIssue: '고객',
    productionSite: '유럽',
    oemLibNm: 'VALEO',
    category: '사양',
    itemNm: 'HV PTC Heater',
    projectNm: 'NOVA MCE',
    description: 'TR 대응\n20260125: TR 최종 제출 완료\n20260110: 2차 수정 진행\nVALEO TR 요청사항 대응',
    importance: '1',
    importanceNm: '하',
    status: 'ING',
    strDt: '2025-03-27',
    finDt: '2026-01-29',
    duration: '308',
    sop: '2025-10-24',
    volum: '50000',
    remark: 'TR 진행 중',
    managerTeam: '기술팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-047',
    issueStateNm: '진행중',
    issueManagerNm: '이기술',
    assignedTo: '이기술',
    openIssueGroup: 32,
    openIssueCategoryOid: 3,
    groupCategoryOid: 1
  },
  {
    oid: 43,
    type: 'DEPT',
    placeOfIssue: '고객',
    productionSite: '인도',
    oemLibNm: 'TATA',
    category: '사양',
    itemNm: 'LV PTC Heater',
    projectNm: 'TATA EV',
    description: '기술 검토\n20260125: 기술 사양 검토 완료\n20260110: 초기 검토 시작\nTATA 전기차 프로젝트',
    importance: '3',
    importanceNm: '상',
    status: 'OPEN',
    strDt: '2025-08-31',
    finDt: '2026-01-29',
    duration: '151',
    sop: '2030-03-31',
    volum: '135000',
    remark: '인도 대형 OEM 프로젝트',
    managerTeam: '기술팀',
    management: 'true',
    report: 'Y',
    issueNo: 'OI-2026-043',
    issueStateNm: '검토중',
    issueManagerNm: '박기술',
    assignedTo: '박기술',
    openIssueGroup: 31,
    openIssueCategoryOid: 3,
    groupCategoryOid: 2
  },
  {
    oid: 39,
    type: 'DEPT',
    placeOfIssue: '고객',
    productionSite: '일본',
    oemLibNm: 'MITSUBISHI',
    category: '사양',
    itemNm: 'LV PTC Heater',
    projectNm: 'Daihatsu LV PTC',
    description: 'TR Q&A 완료\n20260129: 최종 승인 완료\n20260115: 마지막 Q&A 대응\n장기 TR 프로젝트 완료',
    importance: '2',
    importanceNm: '중',
    status: 'CLOSE',
    strDt: '2023-04-12',
    finDt: '2026-01-29',
    duration: '1023',
    sop: '2027-03-31',
    volum: '120000',
    remark: 'TR 승인 완료',
    managerTeam: '기술팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-039',
    issueStateNm: '완료',
    issueManagerNm: '최기술',
    assignedTo: '최기술',
    openIssueGroup: 32,
    openIssueCategoryOid: 3,
    groupCategoryOid: 1
  },
  {
    oid: 37,
    type: 'DEPT',
    placeOfIssue: '고객',
    productionSite: '일본',
    oemLibNm: 'MAZDA',
    category: '사양',
    itemNm: 'HV PTC Heater',
    projectNm: '5Q45V',
    description: '기술 검토\n20260201: 2차 기술 미팅 완료\n20260115: 초기 사양 검토\nMAZDA HV PTC 프로젝트',
    importance: '3',
    importanceNm: '상',
    status: 'OPEN',
    strDt: '2025-12-14',
    finDt: '2026-04-29',
    duration: '136',
    sop: '2029-10-31',
    volum: '240000',
    remark: '일본 대형 OEM 프로젝트',
    managerTeam: '기술팀',
    management: 'true',
    report: 'Y',
    issueNo: 'OI-2026-037',
    issueStateNm: '검토중',
    issueManagerNm: '한청훤',
    assignedTo: '한청훤',
    openIssueGroup: 31,
    openIssueCategoryOid: 3,
    groupCategoryOid: 2
  },
  {
    oid: 31,
    type: 'DEPT',
    placeOfIssue: '고객',
    productionSite: '인도',
    oemLibNm: 'MAHINDRA',
    category: '사양',
    itemNm: 'LV PTC Heater',
    projectNm: 'MAHINDRA P212',
    description: '기술검토\n20260125: 기술 검토 진행 중\n20260110: 사양 협의 시작\nMAHINDRA 전기차 프로젝트',
    importance: '1',
    importanceNm: '하',
    status: 'OPEN',
    strDt: '2024-09-17',
    finDt: '2026-01-29',
    duration: '499',
    sop: '2025-12-31',
    volum: '50000',
    remark: '인도 시장 확대',
    managerTeam: '기술팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-031',
    issueStateNm: '검토중',
    issueManagerNm: '정기술',
    assignedTo: '정기술',
    openIssueGroup: 31,
    openIssueCategoryOid: 3,
    groupCategoryOid: 1
  },
  {
    oid: 26,
    type: 'DEPT',
    placeOfIssue: '고객',
    productionSite: '인도',
    oemLibNm: 'MARUTI SUZUKI',
    category: '사양',
    itemNm: 'LV PTC Heater',
    projectNm: 'e-Tractor',
    description: '수주 추진\n20260125: 견적 제출 완료\n20260110: 기술 검토 진행\n인도 전기 트랙터 프로젝트',
    importance: '1',
    importanceNm: '하',
    status: 'ING',
    strDt: '2024-09-17',
    finDt: '2026-01-29',
    duration: '499',
    sop: '2025-12-31',
    volum: '50000',
    remark: '농기계 시장 진출',
    managerTeam: '영업팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-026',
    issueStateNm: '진행중',
    issueManagerNm: '윤인도',
    assignedTo: '윤인도',
    openIssueGroup: 11,
    openIssueCategoryOid: 1,
    groupCategoryOid: 1
  },
  {
    oid: 22,
    type: 'DEPT',
    placeOfIssue: '고객',
    productionSite: '일본',
    oemLibNm: 'SONGZ',
    category: '사양',
    itemNm: 'HV PTC Heater',
    projectNm: 'SUBARU 500W 후속',
    description: '견적 제출\n20260201: 수정 견적 제출\n20260115: 초기 견적 검토\nSUBARU 후속 모델 프로젝트',
    importance: '1',
    importanceNm: '하',
    status: 'OPEN',
    strDt: '2025-10-02',
    finDt: '2026-02-26',
    duration: '147',
    sop: '2028-12-31',
    volum: '1900000',
    remark: '대량 양산 프로젝트',
    managerTeam: '영업팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-022',
    issueStateNm: '진행중',
    issueManagerNm: '송일본',
    assignedTo: '송일본',
    openIssueGroup: 15,
    openIssueCategoryOid: 1,
    groupCategoryOid: 1
  },
  {
    oid: 15,
    type: 'DEPT',
    placeOfIssue: '고객',
    productionSite: '중국',
    oemLibNm: 'SANDEN',
    category: '사양',
    itemNm: 'HV PTC Heater',
    projectNm: 'TBD (1000W)',
    description: '기술 검토\n20260201: 기술 사양 검토 진행\n20260115: 초기 미팅 완료\nSANDEN 1000W 신규 프로젝트',
    importance: '1',
    importanceNm: '하',
    status: 'OPEN',
    strDt: '2025-10-28',
    finDt: '2026-02-26',
    duration: '121',
    sop: '2029-07-31',
    volum: '456000',
    remark: '신규 용량 개발',
    managerTeam: '기술팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-015',
    issueStateNm: '검토중',
    issueManagerNm: '강기술',
    assignedTo: '강기술',
    openIssueGroup: 31,
    openIssueCategoryOid: 3,
    groupCategoryOid: 1
  },
  {
    oid: 10,
    type: 'DEPT',
    placeOfIssue: '고객',
    productionSite: '중국',
    oemLibNm: 'YUXIN',
    category: '사양',
    itemNm: 'HV PTC Heater',
    projectNm: 'Yuxin EV',
    description: '수주 추진\n20260201: 최종 협상 진행 중\n20260115: 기술 사양 확정\n대형 중국 EV 프로젝트',
    importance: '3',
    importanceNm: '상',
    status: 'OPEN',
    strDt: '2025-09-15',
    finDt: '2026-03-31',
    duration: '197',
    sop: '2028-06-01',
    volum: '800000',
    remark: '중국 대형 EV 프로젝트',
    managerTeam: '영업팀',
    management: 'true',
    report: 'Y',
    issueNo: 'OI-2026-010',
    issueStateNm: '진행중',
    issueManagerNm: '조중국',
    assignedTo: '조중국',
    openIssueGroup: 11,
    openIssueCategoryOid: 1,
    groupCategoryOid: 2
  },
  // ===== 추가 데이터: 해외법인 =====
  {
    oid: 90,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '인도',
    oemLibNm: 'SUBROS',
    category: '기타',
    itemNm: 'LV PTC Heater',
    projectNm: 'WII 생산 확대',
    description: '인도법인 생산라인 증설\n20260203: 설비 발주 완료\n20260201: 투자 승인 완료',
    importance: '2',
    importanceNm: '중',
    status: 'OPEN',
    strDt: '2026-02-01',
    finDt: '2026-06-30',
    duration: '149',
    sop: '',
    volum: '',
    remark: '인도법인 증설',
    managerTeam: '해외법인',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-090',
    issueStateNm: '진행중',
    issueManagerNm: '인도법인장',
    assignedTo: '인도법인장',
    openIssueGroup: 81,
    openIssueCategoryOid: 8,
    groupCategoryOid: 1
  },
  {
    oid: 91,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '중국',
    oemLibNm: 'All',
    category: '기타',
    itemNm: 'All',
    projectNm: 'WRC 품질 개선',
    description: '중국법인 품질 개선 프로젝트\n20260202: 개선 계획 수립 완료\n20260130: 품질 현황 분석 완료',
    importance: '2',
    importanceNm: '중',
    status: 'OPEN',
    strDt: '2026-01-30',
    finDt: '2026-04-30',
    duration: '90',
    sop: '',
    volum: '',
    remark: '중국법인 품질 강화',
    managerTeam: '해외법인',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-091',
    issueStateNm: '진행중',
    issueManagerNm: '중국법인장',
    assignedTo: '중국법인장',
    openIssueGroup: 82,
    openIssueCategoryOid: 8,
    groupCategoryOid: 1
  },
  {
    oid: 92,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '태국',
    oemLibNm: 'DENSO',
    category: '기타',
    itemNm: 'LV PTC Heater',
    projectNm: 'WRT 신규 라인',
    description: '태국법인 신규 라인 구축\n20260203: 레이아웃 설계 완료\n20260128: 프로젝트 킥오프',
    importance: '2',
    importanceNm: '중',
    status: 'OPEN',
    strDt: '2026-01-28',
    finDt: '2026-08-31',
    duration: '215',
    sop: '2027-01-01',
    volum: '45000',
    remark: '태국법인 확장',
    managerTeam: '해외법인',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-092',
    issueStateNm: '진행중',
    issueManagerNm: '태국법인장',
    assignedTo: '태국법인장',
    openIssueGroup: 83,
    openIssueCategoryOid: 8,
    groupCategoryOid: 1
  },
  // ===== 추가 데이터: 품질 감사 =====
  {
    oid: 93,
    type: 'DEPT',
    placeOfIssue: '고객',
    productionSite: '일본',
    oemLibNm: 'DENSO',
    category: '품질',
    itemNm: 'All',
    projectNm: 'DENSO 품질감사',
    description: 'DENSO 정기 품질감사\n20260210: 감사 일정 확정\n20260205: 사전 준비 완료',
    importance: '3',
    importanceNm: '상',
    status: 'OPEN',
    strDt: '2026-02-05',
    finDt: '2026-02-20',
    duration: '15',
    sop: '',
    volum: '',
    remark: '연간 정기 감사',
    managerTeam: '품질관리팀',
    management: 'true',
    report: 'Y',
    issueNo: 'OI-2026-093',
    issueStateNm: '진행중',
    issueManagerNm: '이감사',
    assignedTo: '이감사',
    openIssueGroup: 23,
    openIssueCategoryOid: 2,
    groupCategoryOid: 2
  },
  // ===== 추가 데이터: 설계 변경 =====
  {
    oid: 94,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '본사',
    oemLibNm: 'SUBROS',
    category: '사양',
    itemNm: 'LV PTC Heater',
    projectNm: '240W 설계 변경',
    description: '설계 변경 요청\n20260204: ECN 작성 완료\n20260202: 설계 변경 검토 완료',
    importance: '2',
    importanceNm: '중',
    status: 'OPEN',
    strDt: '2026-02-02',
    finDt: '2026-02-28',
    duration: '26',
    sop: '',
    volum: '',
    remark: '원가 절감 설계변경',
    managerTeam: '기술팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-094',
    issueStateNm: '진행중',
    issueManagerNm: '김설계',
    assignedTo: '김설계',
    openIssueGroup: 33,
    openIssueCategoryOid: 3,
    groupCategoryOid: 1
  },
  // ===== 추가 데이터: 협력업체 =====
  {
    oid: 95,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '본사',
    oemLibNm: 'All',
    category: '기타',
    itemNm: 'All',
    projectNm: '협력업체 평가',
    description: '2026년 협력업체 정기 평가\n20260205: 평가 기준 확정\n20260201: 평가 대상 선정 완료',
    importance: '1',
    importanceNm: '하',
    status: 'OPEN',
    strDt: '2026-02-01',
    finDt: '2026-03-15',
    duration: '42',
    sop: '',
    volum: '',
    remark: '연간 정기 평가',
    managerTeam: '구매팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-095',
    issueStateNm: '진행중',
    issueManagerNm: '박구매',
    assignedTo: '박구매',
    openIssueGroup: 52,
    openIssueCategoryOid: 5,
    groupCategoryOid: 1
  },
  // ===== 추가 데이터: 생산성 향상 =====
  {
    oid: 96,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '본사',
    oemLibNm: 'All',
    category: '기타',
    itemNm: 'HV PTC Heater',
    projectNm: '생산성 향상',
    description: 'HV PTC 라인 생산성 향상\n20260205: 개선안 수립 완료\n20260201: 현황 분석 완료',
    importance: '2',
    importanceNm: '중',
    status: 'OPEN',
    strDt: '2026-02-01',
    finDt: '2026-04-30',
    duration: '88',
    sop: '',
    volum: '',
    remark: '10% 생산성 향상 목표',
    managerTeam: '생산팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-096',
    issueStateNm: '진행중',
    issueManagerNm: '최생산',
    assignedTo: '최생산',
    openIssueGroup: 64,
    openIssueCategoryOid: 6,
    groupCategoryOid: 1
  },
  // ===== 추가 데이터: 시험 평가 =====
  {
    oid: 97,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '본사',
    oemLibNm: 'MAZDA',
    category: '사양',
    itemNm: 'HV PTC Heater',
    projectNm: '5Q45V 신뢰성 시험',
    description: 'MAZDA 5Q45V 신뢰성 시험\n20260204: 시험 진행 중\n20260201: 시험 시작',
    importance: '3',
    importanceNm: '상',
    status: 'OPEN',
    strDt: '2026-02-01',
    finDt: '2026-03-15',
    duration: '42',
    sop: '',
    volum: '',
    remark: '고객 승인 필수',
    managerTeam: '기술팀',
    management: 'true',
    report: 'Y',
    issueNo: 'OI-2026-097',
    issueStateNm: '진행중',
    issueManagerNm: '시험팀장',
    assignedTo: '시험팀장',
    openIssueGroup: 34,
    openIssueCategoryOid: 3,
    groupCategoryOid: 2
  },
  // ===== 추가 데이터: IT 시스템 =====
  {
    oid: 98,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '본사',
    oemLibNm: 'All',
    category: '기타',
    itemNm: 'All',
    projectNm: 'PLM 시스템 개선',
    description: 'PLM 시스템 기능 개선\n20260205: 요구사항 정의 완료\n20260201: 현황 분석 완료',
    importance: '2',
    importanceNm: '중',
    status: 'OPEN',
    strDt: '2026-02-01',
    finDt: '2026-06-30',
    duration: '149',
    sop: '',
    volum: '',
    remark: 'IT 시스템 고도화',
    managerTeam: 'IT팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-098',
    issueStateNm: '진행중',
    issueManagerNm: '이시스템',
    assignedTo: '이시스템',
    openIssueGroup: 72,
    openIssueCategoryOid: 7,
    groupCategoryOid: 1
  },
  // ===== DEV 타입 데이터 추가 =====
  {
    oid: 1001,
    type: 'DEV',
    placeOfIssue: '내부',
    productionSite: '일본',
    oemLibNm: 'SANDEN',
    category: '사양',
    itemNm: 'HV PTC Heater',
    projectNm: 'SANDEN 5kW',
    description: '개발 진행\n20260205: 설계 리뷰 완료\n20260201: 상세 설계 진행 중',
    importance: '3',
    importanceNm: '상',
    status: 'OPEN',
    strDt: '2026-01-15',
    finDt: '2026-06-30',
    duration: '166',
    sop: '2030-06-01',
    volum: '200000',
    remark: 'HV PTC 개발',
    managerTeam: '기술팀',
    management: 'true',
    report: 'Y',
    issueNo: 'DEV-2026-001',
    issueStateNm: '진행중',
    issueManagerNm: '한청훤',
    assignedTo: '한청훤',
    openIssueGroup: 101,
    openIssueCategoryOid: 100,
    groupCategoryOid: 1
  },
  {
    oid: 1002,
    type: 'DEV',
    placeOfIssue: '내부',
    productionSite: '일본',
    oemLibNm: 'MAZDA',
    category: '사양',
    itemNm: 'HV PTC Heater',
    projectNm: 'MAZDA 5Q45V',
    description: '개발 진행\n20260204: 프로토타입 제작 중\n20260201: 설계 검토 완료',
    importance: '3',
    importanceNm: '상',
    status: 'OPEN',
    strDt: '2026-01-10',
    finDt: '2026-05-31',
    duration: '141',
    sop: '2029-10-31',
    volum: '240000',
    remark: 'HV PTC 개발',
    managerTeam: '기술팀',
    management: 'true',
    report: 'Y',
    issueNo: 'DEV-2026-002',
    issueStateNm: '진행중',
    issueManagerNm: '박개발',
    assignedTo: '박개발',
    openIssueGroup: 102,
    openIssueCategoryOid: 100,
    groupCategoryOid: 1
  },
  {
    oid: 1003,
    type: 'DEV',
    placeOfIssue: '내부',
    productionSite: '중국',
    oemLibNm: 'Xiaomi',
    category: '사양',
    itemNm: 'HV PTC Heater',
    projectNm: 'Xiaomi MMA',
    description: '개발 진행\n20260205: 양산 설계 진행 중\n20260201: 고객 승인 완료',
    importance: '3',
    importanceNm: '상',
    status: 'OPEN',
    strDt: '2026-01-05',
    finDt: '2026-08-31',
    duration: '238',
    sop: '2027-12-31',
    volum: '1700000',
    remark: 'HV PTC 대형 개발',
    managerTeam: '기술팀',
    management: 'true',
    report: 'Y',
    issueNo: 'DEV-2026-003',
    issueStateNm: '진행중',
    issueManagerNm: '채지훈',
    assignedTo: '채지훈',
    openIssueGroup: 103,
    openIssueCategoryOid: 100,
    groupCategoryOid: 2
  },
  {
    oid: 1004,
    type: 'DEV',
    placeOfIssue: '내부',
    productionSite: '인도',
    oemLibNm: 'SUBROS',
    category: '사양',
    itemNm: 'LV PTC Heater',
    projectNm: 'SUBROS 240W',
    description: '개발 진행\n20260204: 시험 평가 진행 중\n20260201: 샘플 제작 완료',
    importance: '2',
    importanceNm: '중',
    status: 'OPEN',
    strDt: '2026-01-20',
    finDt: '2026-04-30',
    duration: '100',
    sop: '2027-06-01',
    volum: '75000',
    remark: 'LV PTC 개발',
    managerTeam: '기술팀',
    management: 'false',
    report: 'N',
    issueNo: 'DEV-2026-004',
    issueStateNm: '진행중',
    issueManagerNm: '김개발',
    assignedTo: '김개발',
    openIssueGroup: 201,
    openIssueCategoryOid: 200,
    groupCategoryOid: 1
  },
  {
    oid: 1005,
    type: 'DEV',
    placeOfIssue: '내부',
    productionSite: '일본',
    oemLibNm: 'SUZUKI',
    category: '사양',
    itemNm: 'Coolant Valve',
    projectNm: 'SUZUKI 4Way',
    description: '개발 진행\n20260205: 설계 검토 완료\n20260201: 고객 요구사항 분석 완료',
    importance: '3',
    importanceNm: '상',
    status: 'OPEN',
    strDt: '2026-02-01',
    finDt: '2026-07-31',
    duration: '180',
    sop: '2028-03-01',
    volum: '120000',
    remark: 'Coolant Valve 신규 개발',
    managerTeam: '기술팀',
    management: 'true',
    report: 'Y',
    issueNo: 'DEV-2026-005',
    issueStateNm: '진행중',
    issueManagerNm: '이밸브',
    assignedTo: '이밸브',
    openIssueGroup: 301,
    openIssueCategoryOid: 300,
    groupCategoryOid: 1
  },
  {
    oid: 1006,
    type: 'DEV',
    placeOfIssue: '내부',
    productionSite: '중국',
    oemLibNm: 'LANTU',
    category: '사양',
    itemNm: 'Coolant Heater',
    projectNm: 'LANTU H37',
    description: '양산 개발 완료\n20260201: 양산 승인 완료\n20260115: 최종 시험 완료',
    importance: '1',
    importanceNm: '하',
    status: 'CLOSE',
    strDt: '2025-06-01',
    finDt: '2026-02-01',
    duration: '245',
    sop: '2024-01-01',
    volum: '4000',
    remark: 'Coolant Heater 양산',
    managerTeam: '기술팀',
    management: 'false',
    report: 'N',
    issueNo: 'DEV-2026-006',
    issueStateNm: '완료',
    issueManagerNm: '최개발',
    assignedTo: '최개발',
    openIssueGroup: 401,
    openIssueCategoryOid: 400,
    groupCategoryOid: 1
  },
  // ===== 품질관리팀 추가 데이터 =====
  {
    oid: 100,
    type: 'DEPT',
    placeOfIssue: '고객',
    productionSite: '중국',
    oemLibNm: 'Xiaomi',
    category: '품질',
    itemNm: 'HV PTC Heater',
    projectNm: 'MMA 품질이슈',
    description: '품질 이슈 대응\n20260205: 8D 리포트 작성 중\n20260203: 불량 샘플 분석 완료',
    importance: '3',
    importanceNm: '상',
    status: 'OPEN',
    strDt: '2026-02-03',
    finDt: '2026-02-15',
    duration: '12',
    sop: '',
    volum: '',
    remark: '긴급 품질 이슈',
    managerTeam: '품질관리팀',
    management: 'true',
    report: 'Y',
    issueNo: 'OI-2026-100',
    issueStateNm: '진행중',
    issueState: '78102',
    issueManagerNm: '김품질',
    assignedTo: '김품질',
    openIssueGroup: 21,
    openIssueCategoryOid: 2,
    groupCategoryOid: 1
  },
  {
    oid: 101,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '본사',
    oemLibNm: 'All',
    category: '품질',
    itemNm: 'All',
    projectNm: '내부 품질감사',
    description: '2026년 1분기 내부 품질감사\n20260204: 감사 체크리스트 작성 완료\n20260201: 감사 계획 수립',
    importance: '2',
    importanceNm: '중',
    status: 'OPEN',
    strDt: '2026-02-01',
    finDt: '2026-02-28',
    duration: '27',
    sop: '',
    volum: '',
    remark: '분기별 정기 감사',
    managerTeam: '품질관리팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-101',
    issueStateNm: '진행중',
    issueState: '78102',
    issueManagerNm: '박감사',
    assignedTo: '박감사',
    openIssueGroup: 24,
    openIssueCategoryOid: 2,
    groupCategoryOid: 1
  },
  {
    oid: 102,
    type: 'DEPT',
    placeOfIssue: '고객',
    productionSite: '인도',
    oemLibNm: 'TATA',
    category: '품질',
    itemNm: 'LV PTC Heater',
    projectNm: 'TATA 클레임',
    description: '클레임 대응\n20260205: 대책서 작성 완료\n20260202: 현장 조사 완료',
    importance: '4',
    importanceNm: '지시사항',
    status: 'OPEN',
    strDt: '2026-02-02',
    finDt: '2026-02-10',
    duration: '8',
    sop: '',
    volum: '',
    remark: '경영진 지시 사항',
    managerTeam: '품질관리팀',
    management: 'true',
    report: 'Y',
    issueNo: 'OI-2026-102',
    issueStateNm: '진행중',
    issueState: '78102',
    issueManagerNm: '이클레임',
    assignedTo: '이클레임',
    openIssueGroup: 22,
    openIssueCategoryOid: 2,
    groupCategoryOid: 1
  },
  {
    oid: 103,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '본사',
    oemLibNm: 'All',
    category: '품질',
    itemNm: 'HV PTC Heater',
    projectNm: '불량률 분석',
    description: '월간 불량률 분석\n20260205: 1월 불량 데이터 분석 완료\n20260203: 데이터 수집 완료',
    importance: '2',
    importanceNm: '중',
    status: 'CLOSE',
    strDt: '2026-02-01',
    finDt: '2026-02-05',
    duration: '4',
    sop: '',
    volum: '',
    remark: '월간 정기 분석',
    managerTeam: '품질관리팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-103',
    issueStateNm: '완료',
    issueState: '78106',
    issueManagerNm: '최분석',
    assignedTo: '최분석',
    openIssueGroup: 25,
    openIssueCategoryOid: 2,
    groupCategoryOid: 1
  },
  // ===== 구매팀 추가 데이터 =====
  {
    oid: 110,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '본사',
    oemLibNm: 'All',
    category: '기타',
    itemNm: 'All',
    projectNm: '납기 지연 관리',
    description: '협력업체 납기 지연 이슈\n20260205: 대체 업체 검토 중\n20260203: 납기 지연 현황 파악 완료',
    importance: '5',
    importanceNm: '긴급',
    status: 'OPEN',
    strDt: '2026-02-03',
    finDt: '2026-02-08',
    duration: '5',
    sop: '',
    volum: '',
    remark: '긴급 납기 대응',
    managerTeam: '구매팀',
    management: 'true',
    report: 'Y',
    issueNo: 'OI-2026-110',
    issueStateNm: '진행중',
    issueState: '78102',
    issueManagerNm: '김납기',
    assignedTo: '김납기',
    openIssueGroup: 53,
    openIssueCategoryOid: 5,
    groupCategoryOid: 1
  },
  {
    oid: 111,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '본사',
    oemLibNm: 'All',
    category: '기타',
    itemNm: 'PTC Element',
    projectNm: '원가 절감 TF',
    description: '원가 절감 활동\n20260204: 3개 품목 절감안 확정\n20260201: 절감 대상 품목 선정',
    importance: '2',
    importanceNm: '중',
    status: 'OPEN',
    strDt: '2026-02-01',
    finDt: '2026-03-31',
    duration: '58',
    sop: '',
    volum: '',
    remark: '연간 5% 절감 목표',
    managerTeam: '구매팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-111',
    issueStateNm: '진행중',
    issueState: '78102',
    issueManagerNm: '이원가',
    assignedTo: '이원가',
    openIssueGroup: 54,
    openIssueCategoryOid: 5,
    groupCategoryOid: 1
  },
  {
    oid: 112,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '중국',
    oemLibNm: 'All',
    category: '기타',
    itemNm: 'All',
    projectNm: '중국 협력업체 관리',
    description: '중국 협력업체 품질/납기 관리\n20260205: 월간 실적 검토 완료\n20260201: 현황 자료 수집',
    importance: '2',
    importanceNm: '중',
    status: 'OPEN',
    strDt: '2026-02-01',
    finDt: '2026-02-28',
    duration: '27',
    sop: '',
    volum: '',
    remark: '중국 공급망 관리',
    managerTeam: '구매팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-112',
    issueStateNm: '진행중',
    issueState: '78102',
    issueManagerNm: '박협력',
    assignedTo: '박협력',
    openIssueGroup: 52,
    openIssueCategoryOid: 5,
    groupCategoryOid: 1
  },
  {
    oid: 113,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '본사',
    oemLibNm: 'All',
    category: '기타',
    itemNm: 'Copper Wire',
    projectNm: '구리선 단가 협상',
    description: '원자재 단가 협상\n20260130: 협상 완료, 3% 인하 합의\n20260125: 협상 시작',
    importance: '1',
    importanceNm: '하',
    status: 'CLOSE',
    strDt: '2026-01-25',
    finDt: '2026-01-30',
    duration: '5',
    sop: '',
    volum: '',
    remark: '단가 협상 완료',
    managerTeam: '구매팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-113',
    issueStateNm: '완료',
    issueState: '78106',
    issueManagerNm: '최단가',
    assignedTo: '최단가',
    openIssueGroup: 51,
    openIssueCategoryOid: 5,
    groupCategoryOid: 1
  },
  // ===== 생산팀 추가 데이터 =====
  {
    oid: 120,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '본사',
    oemLibNm: 'All',
    category: '기타',
    itemNm: 'HV PTC Heater',
    projectNm: '설비 예방정비',
    description: '월간 예방정비 계획\n20260205: 정비 완료\n20260201: 정비 계획 수립',
    importance: '1',
    importanceNm: '하',
    status: 'CLOSE',
    strDt: '2026-02-01',
    finDt: '2026-02-05',
    duration: '4',
    sop: '',
    volum: '',
    remark: '월간 정기 정비',
    managerTeam: '생산팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-120',
    issueStateNm: '완료',
    issueState: '78106',
    issueManagerNm: '김설비',
    assignedTo: '김설비',
    openIssueGroup: 62,
    openIssueCategoryOid: 6,
    groupCategoryOid: 1
  },
  {
    oid: 121,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '본사',
    oemLibNm: 'Xiaomi',
    category: '기타',
    itemNm: 'HV PTC Heater',
    projectNm: 'Xiaomi 라인 증설',
    description: '신규 라인 증설 프로젝트\n20260205: 설비 발주 검토 중\n20260201: 레이아웃 확정',
    importance: '3',
    importanceNm: '상',
    status: 'OPEN',
    strDt: '2026-02-01',
    finDt: '2026-06-30',
    duration: '149',
    sop: '2027-01-01',
    volum: '500000',
    remark: '대형 프로젝트 대응',
    managerTeam: '생산팀',
    management: 'true',
    report: 'Y',
    issueNo: 'OI-2026-121',
    issueStateNm: '진행중',
    issueState: '78102',
    issueManagerNm: '이증설',
    assignedTo: '이증설',
    openIssueGroup: 63,
    openIssueCategoryOid: 6,
    groupCategoryOid: 2
  },
  {
    oid: 122,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '본사',
    oemLibNm: 'DENSO',
    category: '기타',
    itemNm: 'LV PTC Heater',
    projectNm: '양산 라인 이슈',
    description: '양산 중 품질 이슈 발생\n20260204: 원인 분석 중\n20260203: 이슈 발생 보고',
    importance: '4',
    importanceNm: '지시사항',
    status: 'OPEN',
    strDt: '2026-02-03',
    finDt: '2026-02-10',
    duration: '7',
    sop: '',
    volum: '',
    remark: '긴급 대응 필요',
    managerTeam: '생산팀',
    management: 'true',
    report: 'Y',
    issueNo: 'OI-2026-122',
    issueStateNm: '진행중',
    issueState: '78102',
    issueManagerNm: '박양산',
    assignedTo: '박양산',
    openIssueGroup: 61,
    openIssueCategoryOid: 6,
    groupCategoryOid: 1
  },
  {
    oid: 123,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '본사',
    oemLibNm: 'All',
    category: '기타',
    itemNm: 'Coolant Valve',
    projectNm: 'CV 생산성 향상',
    description: 'Coolant Valve 라인 개선\n20260204: 개선안 검토 완료\n20260201: 현황 분석 완료',
    importance: '2',
    importanceNm: '중',
    status: 'OPEN',
    strDt: '2026-02-01',
    finDt: '2026-04-30',
    duration: '88',
    sop: '',
    volum: '',
    remark: '15% 생산성 향상 목표',
    managerTeam: '생산팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-123',
    issueStateNm: '진행중',
    issueState: '78102',
    issueManagerNm: '최생산',
    assignedTo: '최생산',
    openIssueGroup: 64,
    openIssueCategoryOid: 6,
    groupCategoryOid: 1
  },
  // ===== IT팀 추가 데이터 =====
  {
    oid: 130,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '본사',
    oemLibNm: 'All',
    category: '기타',
    itemNm: 'All',
    projectNm: '보안 점검',
    description: '월간 보안 점검\n20260205: 점검 완료, 이상 없음\n20260201: 점검 시작',
    importance: '2',
    importanceNm: '중',
    status: 'CLOSE',
    strDt: '2026-02-01',
    finDt: '2026-02-05',
    duration: '4',
    sop: '',
    volum: '',
    remark: '정기 보안 점검',
    managerTeam: 'IT팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-130',
    issueStateNm: '완료',
    issueState: '78106',
    issueManagerNm: '김보안',
    assignedTo: '김보안',
    openIssueGroup: 73,
    openIssueCategoryOid: 7,
    groupCategoryOid: 1
  },
  {
    oid: 131,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '본사',
    oemLibNm: 'All',
    category: '기타',
    itemNm: 'All',
    projectNm: 'ERP 모듈 개선',
    description: 'ERP 생산관리 모듈 개선\n20260205: 요구사항 분석 완료\n20260201: 현업 요청 접수',
    importance: '2',
    importanceNm: '중',
    status: 'OPEN',
    strDt: '2026-02-01',
    finDt: '2026-04-30',
    duration: '88',
    sop: '',
    volum: '',
    remark: 'ERP 기능 개선',
    managerTeam: 'IT팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-131',
    issueStateNm: '진행중',
    issueState: '78102',
    issueManagerNm: '이ERP',
    assignedTo: '이ERP',
    openIssueGroup: 71,
    openIssueCategoryOid: 7,
    groupCategoryOid: 1
  },
  {
    oid: 132,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '본사',
    oemLibNm: 'All',
    category: '기타',
    itemNm: 'All',
    projectNm: 'Open Issue 시스템',
    description: 'Open Issue 관리 시스템 개발\n20260205: 개발 진행 중\n20260115: 프로젝트 착수',
    importance: '3',
    importanceNm: '상',
    status: 'OPEN',
    strDt: '2026-01-15',
    finDt: '2026-03-31',
    duration: '75',
    sop: '',
    volum: '',
    remark: 'IT 신규 프로젝트',
    managerTeam: 'IT팀',
    management: 'true',
    report: 'Y',
    issueNo: 'OI-2026-132',
    issueStateNm: '진행중',
    issueState: '78102',
    issueManagerNm: '박시스템',
    assignedTo: '박시스템',
    openIssueGroup: 72,
    openIssueCategoryOid: 7,
    groupCategoryOid: 1
  },
  // ===== 해외법인 추가 데이터 =====
  {
    oid: 140,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '인도',
    oemLibNm: 'MAHINDRA',
    category: '기타',
    itemNm: 'LV PTC Heater',
    projectNm: 'WII 신규 수주',
    description: '인도법인 신규 수주 활동\n20260205: 견적 제출 완료\n20260201: 고객 미팅 완료',
    importance: '3',
    importanceNm: '상',
    status: 'OPEN',
    strDt: '2026-02-01',
    finDt: '2026-03-31',
    duration: '58',
    sop: '2027-12-01',
    volum: '80000',
    remark: '인도법인 성장 전략',
    managerTeam: '해외법인',
    management: 'true',
    report: 'Y',
    issueNo: 'OI-2026-140',
    issueStateNm: '진행중',
    issueState: '78102',
    issueManagerNm: '인도영업',
    assignedTo: '인도영업',
    openIssueGroup: 81,
    openIssueCategoryOid: 8,
    groupCategoryOid: 1
  },
  {
    oid: 141,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '중국',
    oemLibNm: 'Songz',
    category: '기타',
    itemNm: 'Coolant Heater',
    projectNm: 'WRC 양산 이슈',
    description: '중국법인 양산 문제 해결\n20260204: 원인 분석 완료\n20260201: 이슈 접수',
    importance: '5',
    importanceNm: '긴급',
    status: 'OPEN',
    strDt: '2026-02-01',
    finDt: '2026-02-05',
    duration: '4',
    sop: '',
    volum: '',
    remark: '긴급 대응 필요',
    managerTeam: '해외법인',
    management: 'true',
    report: 'Y',
    issueNo: 'OI-2026-141',
    issueStateNm: '진행중',
    issueState: '78102',
    issueManagerNm: '중국생산',
    assignedTo: '중국생산',
    openIssueGroup: 82,
    openIssueCategoryOid: 8,
    groupCategoryOid: 1
  },
  {
    oid: 142,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '태국',
    oemLibNm: 'DENSO',
    category: '기타',
    itemNm: 'LV PTC Heater',
    projectNm: 'WRT 품질 인증',
    description: '태국법인 IATF 인증 준비\n20260205: 문서 준비 중\n20260201: 인증 준비 시작',
    importance: '2',
    importanceNm: '중',
    status: 'OPEN',
    strDt: '2026-02-01',
    finDt: '2026-05-31',
    duration: '119',
    sop: '',
    volum: '',
    remark: '품질 인증 취득',
    managerTeam: '해외법인',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-142',
    issueStateNm: '진행중',
    issueState: '78102',
    issueManagerNm: '태국품질',
    assignedTo: '태국품질',
    openIssueGroup: 83,
    openIssueCategoryOid: 8,
    groupCategoryOid: 1
  },
  {
    oid: 143,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '인도',
    oemLibNm: 'SUBROS',
    category: '기타',
    itemNm: 'LV PTC Heater',
    projectNm: 'WII 인력 충원',
    description: '인도법인 생산인력 충원\n20260130: 채용 완료\n20260115: 채용 공고 게시',
    importance: '1',
    importanceNm: '하',
    status: 'CLOSE',
    strDt: '2026-01-15',
    finDt: '2026-01-30',
    duration: '15',
    sop: '',
    volum: '',
    remark: '인력 충원 완료',
    managerTeam: '해외법인',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-143',
    issueStateNm: '완료',
    issueState: '78106',
    issueManagerNm: '인도인사',
    assignedTo: '인도인사',
    openIssueGroup: 81,
    openIssueCategoryOid: 8,
    groupCategoryOid: 1
  },
  // ===== 영업팀 추가 데이터 =====
  {
    oid: 150,
    type: 'DEPT',
    placeOfIssue: '고객',
    productionSite: '유럽',
    oemLibNm: 'BOSCH',
    category: '사양',
    itemNm: 'HV PTC Heater',
    projectNm: 'BOSCH 신규 RFQ',
    description: '신규 수주 활동\n20260205: RFQ 검토 중\n20260201: RFQ 접수',
    importance: '3',
    importanceNm: '상',
    status: 'OPEN',
    strDt: '2026-02-01',
    finDt: '2026-03-15',
    duration: '42',
    sop: '2029-06-01',
    volum: '300000',
    remark: '유럽 시장 진출',
    managerTeam: '영업팀',
    management: 'true',
    report: 'Y',
    issueNo: 'OI-2026-150',
    issueStateNm: '진행중',
    issueState: '78102',
    issueManagerNm: '유럽영업',
    assignedTo: '유럽영업',
    openIssueGroup: 11,
    openIssueCategoryOid: 1,
    groupCategoryOid: 2
  },
  {
    oid: 151,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '본사',
    oemLibNm: 'MAZDA',
    category: '기타',
    itemNm: 'HV PTC Heater',
    projectNm: '5Q45V 견적 검토',
    description: '견적 검토 및 제출\n20260204: 검토 완료\n20260201: 견적 작성 시작',
    importance: '2',
    importanceNm: '중',
    status: 'CLOSE',
    strDt: '2026-02-01',
    finDt: '2026-02-04',
    duration: '3',
    sop: '',
    volum: '',
    remark: '견적 제출 완료',
    managerTeam: '영업팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-151',
    issueStateNm: '완료',
    issueState: '78106',
    issueManagerNm: '김견적',
    assignedTo: '김견적',
    openIssueGroup: 15,
    openIssueCategoryOid: 1,
    groupCategoryOid: 1
  },
  {
    oid: 152,
    type: 'DEPT',
    placeOfIssue: '고객',
    productionSite: '일본',
    oemLibNm: 'TOYOTA',
    category: '사양',
    itemNm: 'Coolant Valve',
    projectNm: 'TOYOTA CV 기술검토',
    description: '기술 검토 진행\n20260205: 기술 미팅 완료\n20260201: 검토 시작',
    importance: '3',
    importanceNm: '상',
    status: 'OPEN',
    strDt: '2026-02-01',
    finDt: '2026-04-30',
    duration: '88',
    sop: '2029-01-01',
    volum: '450000',
    remark: '대형 OEM 신규 개발',
    managerTeam: '영업팀',
    management: 'true',
    report: 'Y',
    issueNo: 'OI-2026-152',
    issueStateNm: '진행중',
    issueState: '78102',
    issueManagerNm: '일본영업',
    assignedTo: '일본영업',
    openIssueGroup: 12,
    openIssueCategoryOid: 1,
    groupCategoryOid: 2
  },
  // ===== 기술팀 추가 데이터 =====
  {
    oid: 160,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '본사',
    oemLibNm: 'TOYOTA',
    category: '사양',
    itemNm: 'Coolant Valve',
    projectNm: 'TOYOTA CV 설계',
    description: '신규 제품 설계\n20260205: 기본 설계 진행 중\n20260201: 설계 착수',
    importance: '3',
    importanceNm: '상',
    status: 'OPEN',
    strDt: '2026-02-01',
    finDt: '2026-06-30',
    duration: '149',
    sop: '2029-01-01',
    volum: '450000',
    remark: '신규 제품 개발',
    managerTeam: '기술팀',
    management: 'true',
    report: 'Y',
    issueNo: 'OI-2026-160',
    issueStateNm: '진행중',
    issueState: '78102',
    issueManagerNm: '설계팀장',
    assignedTo: '설계팀장',
    openIssueGroup: 33,
    openIssueCategoryOid: 3,
    groupCategoryOid: 2
  },
  {
    oid: 161,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '본사',
    oemLibNm: 'Xiaomi',
    category: '사양',
    itemNm: 'HV PTC Heater',
    projectNm: 'MMA 양산 지원',
    description: '양산 지원 활동\n20260205: 양산 준비 점검 완료\n20260201: 지원 계획 수립',
    importance: '3',
    importanceNm: '상',
    status: 'OPEN',
    strDt: '2026-02-01',
    finDt: '2026-08-31',
    duration: '211',
    sop: '2027-12-31',
    volum: '1700000',
    remark: '대형 프로젝트 양산 지원',
    managerTeam: '기술팀',
    management: 'true',
    report: 'Y',
    issueNo: 'OI-2026-161',
    issueStateNm: '진행중',
    issueState: '78102',
    issueManagerNm: '양산지원',
    assignedTo: '양산지원',
    openIssueGroup: 35,
    openIssueCategoryOid: 3,
    groupCategoryOid: 2
  },
  {
    oid: 162,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '본사',
    oemLibNm: 'SUBROS',
    category: '사양',
    itemNm: 'LV PTC Heater',
    projectNm: '240W 시험평가',
    description: '신뢰성 시험 진행\n20260205: 시험 진행 중\n20260201: 시험 시작',
    importance: '2',
    importanceNm: '중',
    status: 'OPEN',
    strDt: '2026-02-01',
    finDt: '2026-03-15',
    duration: '42',
    sop: '',
    volum: '',
    remark: '신뢰성 시험',
    managerTeam: '기술팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-162',
    issueStateNm: '진행중',
    issueState: '78102',
    issueManagerNm: '시험담당',
    assignedTo: '시험담당',
    openIssueGroup: 34,
    openIssueCategoryOid: 3,
    groupCategoryOid: 1
  },
  // ===== 경영기획팀 추가 데이터 =====
  {
    oid: 170,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '본사',
    oemLibNm: 'All',
    category: '기타',
    itemNm: 'All',
    projectNm: '2026년 사업계획',
    description: '연간 사업계획 수립\n20260205: 최종 확정\n20260115: 검토 완료',
    importance: '3',
    importanceNm: '상',
    status: 'CLOSE',
    strDt: '2026-01-02',
    finDt: '2026-02-05',
    duration: '34',
    sop: '',
    volum: '',
    remark: '연간 사업계획',
    managerTeam: '경영기획팀',
    management: 'true',
    report: 'Y',
    issueNo: 'OI-2026-170',
    issueStateNm: '완료',
    issueState: '78106',
    issueManagerNm: '기획팀장',
    assignedTo: '기획팀장',
    openIssueGroup: 44,
    openIssueCategoryOid: 4,
    groupCategoryOid: 1
  },
  {
    oid: 171,
    type: 'DEPT',
    placeOfIssue: '내부',
    productionSite: '본사',
    oemLibNm: 'All',
    category: '기타',
    itemNm: 'All',
    projectNm: '투자 심의',
    description: '설비 투자 심의\n20260205: 심의 완료\n20260201: 투자 계획 검토',
    importance: '2',
    importanceNm: '중',
    status: 'CLOSE',
    strDt: '2026-02-01',
    finDt: '2026-02-05',
    duration: '4',
    sop: '',
    volum: '',
    remark: '분기별 투자 심의',
    managerTeam: '경영기획팀',
    management: 'false',
    report: 'N',
    issueNo: 'OI-2026-171',
    issueStateNm: '완료',
    issueState: '78106',
    issueManagerNm: '투자담당',
    assignedTo: '투자담당',
    openIssueGroup: 43,
    openIssueCategoryOid: 4,
    groupCategoryOid: 1
  }
];

class OpenIssueService extends ServiceBase {
  getAllOpenIssue(param: OpenIssueSearch, lang?: string) {
    if (DEV_BYPASS_AUTH) {
      console.log('[DEV MODE] Mock Open Issue 목록 반환');
      return Promise.resolve(mockOpenIssueData);
    }
    return this.service.post<OpenIssueType[]>('openIssue', param, { params: { lang } });
  }

  searchOpenIssue(param: OpenIssueSearch, lang?: string) {
    if (DEV_BYPASS_AUTH) {
      console.log('[DEV MODE] Mock Open Issue 검색 결과 반환', param);
      // 필터링 로직
      let filtered = [...mockOpenIssueData];

      // 타입 필터링 (DEPT 또는 DEV)
      if (param.openIssueType) {
        filtered = filtered.filter(item => item.type === param.openIssueType);
      }

      // 팀 필터링 (param.openIssueGroup은 팀 ID, 데이터의 openIssueCategoryOid와 매핑)
      if (param.openIssueGroup && param.openIssueGroup > 0) {
        filtered = filtered.filter(item => item.openIssueCategoryOid === param.openIssueGroup);
      }

      // 하위 그룹 필터링 (param.openIssueCategoryOid는 그룹 ID, 데이터의 openIssueGroup과 매핑)
      if (param.openIssueCategoryOid && param.openIssueCategoryOid > 0) {
        filtered = filtered.filter(item => item.openIssueGroup === param.openIssueCategoryOid);
      }

      // 검색어 필터링
      if (param.searchWord && param.searchWord.trim() !== '') {
        const searchLower = param.searchWord.toLowerCase();
        filtered = filtered.filter(item =>
          item.description?.toLowerCase().includes(searchLower) ||
          item.projectNm?.toLowerCase().includes(searchLower) ||
          item.itemNm?.toLowerCase().includes(searchLower) ||
          item.oemLibNm?.toLowerCase().includes(searchLower) ||
          item.issueNo?.toLowerCase().includes(searchLower) ||
          item.issueManagerNm?.toLowerCase().includes(searchLower)
        );
      }

      // DEPT 칼럼용 필드 매핑 (deptCustomerNm, issueType, deptProjectNm, deptItemNm, contents)
      const result = filtered.map(item => ({
        ...item,
        deptCustomerNm: item.deptCustomerNm || item.oemLibNm || '',
        deptProjectNm: item.deptProjectNm || item.projectNm || '',
        deptItemNm: item.deptItemNm || item.itemNm || '',
        issueType: item.issueType || item.category || '',
        contents: item.contents || (item.description ? item.description.split('\n')[0] : '')
      }));

      console.log('[DEV MODE] 필터링 결과:', result.length, '건');
      return Promise.resolve(result);
    }
    return this.service.post<OpenIssueType[]>('openIssue/search', null, { params: { ...param, lang } });
  }

  getCategory() {
    if (DEV_BYPASS_AUTH) {
      console.log('[DEV MODE] Mock 카테고리 반환');
      return Promise.resolve(mockCategoryData);
    }
    return this.service.get<DLibrary[]>('openIssue/category');
  }

  getOpenIssueMenu(type: string) {
    if (DEV_BYPASS_AUTH) {
      console.log('[DEV MODE] Mock 메뉴 반환:', type);
      return Promise.resolve(mockMenuData[type] || []);
    }
    return this.service.get<OpenIssueMenu[]>(`openIssue/menu/${type}`);
  }

  insOpenIssue(param: IssueValidationType) {
    return this.service.post<IssueValidationType>(`openIssue/registration`, param);
  }

  insOpenIssueV2(param: OpenIssueType[]) {
    return this.service.post<OpenIssueType[]>(`openIssue/registration_v2`, param);
  }

  updateOpenIssue(param: OpenIssueType[]) {
    return this.service.post<OpenIssueType[]>(`openIssue/update`, param);
  }

  removeOpenIssue(oid: number) {
    return this.service.post(`openIssue/remove/${oid}`);
  }

  removeOpenIssueBatch(payload: OpenIssueType[]) {
    return this.service.post(`openIssue/remove/batch`, payload);
  }

  // group

  updateGroup(payload: OpenissueGroup) {
    return this.service.post<OpenissueGroup>(`openIssue/menu/group/update`, payload);
  }

  updateGroupStatus(payload: OpenissueGroup) {
    return this.service.post<OpenissueGroup>(`openIssue/menu/group/status/update`, payload);
  }

  registGroup(payload: Partial<OpenissueGroup>) {
    return this.service.post<OpenissueGroup>(`openIssue/menu/group/registration`, payload);
  }

  removeGroup(oid: string) {
    return this.service.post(`openIssue/menu/group/remove/${oid}`);
  }

  getMember(param: Partial<OpenissueGroup>) {
    if (DEV_BYPASS_AUTH) {
      console.log('[DEV MODE] Mock 멤버 목록 반환');
      return Promise.resolve([
        { oid: 1, name: '김담당', deptName: '품질관리팀' },
        { oid: 2, name: '이담당', deptName: '개발팀' }
      ] as OpenissueGroupMember[]);
    }
    return this.service.get<OpenissueGroupMember[]>(`openIssue/member/${param.fromOid}`);
  }

  getMemberDefault(groupType: string) {
    if (DEV_BYPASS_AUTH) {
      console.log('[DEV MODE] Mock 기본 멤버 반환');
      return Promise.resolve([] as OpenIssueRelationship[]);
    }
    return this.service.get<OpenIssueRelationship[]>(`openIssue/menu/group/default/member`, { params: { groupType } });
  }

  getGroupDetail(oid: number) {
    if (DEV_BYPASS_AUTH) {
      console.log('[DEV MODE] Mock 그룹 상세 반환');
      return Promise.resolve({
        oid: oid,
        name: '테스트 그룹',
        groupType: 'DEPT'
      } as OpenissueGroup);
    }
    return this.service.get<OpenissueGroup>(`openIssue/menu/group/${oid}`);
  }

  // comment

  getCommentList(openIssueOid: number) {
    if (DEV_BYPASS_AUTH) {
      console.log('[DEV MODE] Mock 코멘트 목록 반환');
      return Promise.resolve([
        { oid: 1, openIssueOid, contents: '테스트 코멘트입니다.', createDt: '2026-01-15', creatorNm: '김담당' }
      ] as OpenissueComment[]);
    }
    return this.service.get<OpenissueComment[]>(`openIssue/comment/${openIssueOid}`);
  }

  getCommentDetail(comment: OpenissueComment) {
    return this.service.get<OpenissueComment>(`openIssue/comment/${comment.openIssueOid}/${comment.oid}`);
  }

  removeComment(oid: number) {
    return this.service.post(`openIssue/comment/remove/${oid}`);
  }

  registComment(payload: Partial<OpenissueComment>) {
    return this.service.post<OpenissueComment>(`openIssue/comment/registration`, payload);
  }

  updateComment(payload: Partial<OpenissueComment>) {
    return this.service.post<OpenissueComment>(`openIssue/comment/modify`, payload);
  }

  // group category

  getGroupCategory(openIssueCategoryOid: number) {
    if (DEV_BYPASS_AUTH) {
      console.log('[DEV MODE] Mock 그룹 카테고리 반환');
      return Promise.resolve([
        { oid: 1, name: '일반', ord: 1 },
        { oid: 2, name: '긴급', ord: 2 }
      ] as OpenissueGroupCategory[]);
    }
    return this.service.get<OpenissueGroupCategory[]>(`openIssue/group/category/${openIssueCategoryOid}`);
  }

  // activity log
  getActivityLog(issueOid: number) {
    if (DEV_BYPASS_AUTH) {
      console.log('[DEV MODE] Mock 활동 로그 반환');
      const issue = mockOpenIssueData.find((i) => i.oid === issueOid);
      if (!issue) return Promise.resolve([] as ActivityLog[]);

      const logs: ActivityLog[] = [];
      let id = 1;

      // 이슈 생성 로그
      logs.push({
        id: id++,
        issueOid,
        issueNo: issue.issueNo || '',
        action: 'CREATED' as ActivityAction,
        description: `이슈가 생성되었습니다: ${(issue.description || '').substring(0, 50)}`,
        userName: issue.issueManagerNm || '시스템',
        timestamp: issue.strDt || '2026-01-01'
      });

      // 상태 변경 로그 (완료 상태인 경우)
      if (issue.issueState === '78106' && issue.closeDt) {
        logs.push({
          id: id++,
          issueOid,
          issueNo: issue.issueNo || '',
          action: 'STATUS_CHANGED' as ActivityAction,
          description: '이슈 상태가 변경되었습니다.',
          oldValue: '진행',
          newValue: '완료',
          userName: issue.issueManagerNm || '시스템',
          timestamp: issue.closeDt
        });
      }

      // 담당자 지정 로그
      if (issue.issueManagerNm) {
        logs.push({
          id: id++,
          issueOid,
          issueNo: issue.issueNo || '',
          action: 'MANAGER_ASSIGNED' as ActivityAction,
          description: `담당자가 지정되었습니다: ${issue.issueManagerNm}`,
          newValue: issue.issueManagerNm,
          userName: '시스템',
          timestamp: issue.strDt || '2026-01-01'
        });
      }

      // 파일 첨부 로그
      if (issue.isFileYn === 'Y') {
        logs.push({
          id: id++,
          issueOid,
          issueNo: issue.issueNo || '',
          action: 'FILE_UPLOADED' as ActivityAction,
          description: '파일이 업로드되었습니다.',
          userName: issue.issueManagerNm || '시스템',
          timestamp: issue.strDt || '2026-01-05'
        });
      }

      // 의견 추가 로그
      if (issue.isCommentYn === 'Y') {
        logs.push({
          id: id++,
          issueOid,
          issueNo: issue.issueNo || '',
          action: 'COMMENT_ADDED' as ActivityAction,
          description: '새 의견이 등록되었습니다.',
          userName: issue.issueManagerNm || '시스템',
          timestamp: issue.strDt || '2026-01-10'
        });
      }

      return Promise.resolve(logs.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()));
    }
    return this.service.get<ActivityLog[]>(`openIssue/activity/${issueOid}`);
  }
}
export default new OpenIssueService();
